services:
  timescaledb:
    container_name: scale-db-dev
    image: timescale/timescaledb-ha:pg18-all
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: poultry_db
    volumes:
      - scale_db_data_dev:/var/lib/postgresql/data
    networks:
      - scale-network-dev

  redis:
    container_name: scale-cache-dev
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - scale-network-dev

  mqtt:
    container_name: scale-mqtt-dev
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - scale-network-dev

volumes:
  scale_db_data_dev:

networks:
  scale-network-dev:
    driver: bridge
