apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: scale-app
type: Opaque
stringData:
  # Database
  DB_PASSWORD: "${DB_PASSWORD}"
  # Redis
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  # MQTT
  MQTT_USERNAME: "${MQTT_USERNAME}"
  MQTT_PASSWORD: "${MQTT_PASSWORD}"
  # App specific
  BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  # Monitoring users
  GRAFANA_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
